"""RAMon Chatbot FastAPI server.

This module defines the FastAPI application and routes for the chatbot service.
"""
import logging
from contextlib import asynccontextmanager

from dotenv import load_dotenv
from fastapi import Depends, FastAPI, HTTPException, WebSocket
from fastapi.responses import HTMLResponse
from langgraph.checkpoint.postgres.aio import AsyncShallowPostgresSaver
from pgvector.psycopg import register_vector_async
from psycopg_pool import AsyncConnectionPool
from psycopg.rows import dict_row

from auth import AuthSettings, generate_jwt
from chatbot import ChatbotBuilder, ChatbotService, ChatNotFoundError
from chatbot.adapters import PostgresProductRepository
from config import AppConfig, ConfigError
from dependencies import get_chatbot_service, get_chatbot_service_ws, get_product_catalog_ws
from middleware import require_basic_auth, require_jwt, validate_websocket_token
from websocket_handler import handle_websocket_session, validate_chat_id
from product_catalog import PostgresProductCatalog

logger = logging.getLogger("ramon.server")

load_dotenv()

# Cache the index.html template at module load
with open("index.html", "r") as f:
    INDEX_HTML_TEMPLATE = f.read()


async def _configure_pgvector(conn):
    """Register the pgvector type on each new async connection."""
    await register_vector_async(conn)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan manager for initializing and cleaning up resources."""
    try:
        settings = AppConfig.from_env()
        auth_settings = AuthSettings.from_env()
    except (ConfigError, ValueError) as exc:
        logger.critical("Failed to load configuration: %s", exc)
        raise

    db_pool = AsyncConnectionPool(
        conninfo=settings.database_url,
        min_size=2,
        max_size=10,
        open=False,
        configure=_configure_pgvector,
        kwargs={
            "autocommit": True,
            "row_factory": dict_row
        }
    )
    await db_pool.open()

    # Build chatbot service using the builder pattern
    app.state.chatbot_service = (
        ChatbotBuilder()
        .with_openai(
            api_key=settings.openai_api_key,
            model=settings.openai_model,
            temperature=settings.openai_temperature,
        )
        .with_tavily(api_key=settings.tavily_api_key)
        .with_checkpointer(AsyncShallowPostgresSaver(db_pool))
        .with_product_repository(PostgresProductRepository(db_pool))
        .build()
    )
    app.state.product_catalog = PostgresProductCatalog(db_pool)
    app.state.auth_settings = auth_settings

    yield

    await db_pool.close()


app = FastAPI(title="RAMon Chatbot", lifespan=lifespan)


@app.get("/")
async def root(auth_settings: AuthSettings = Depends(require_basic_auth)):
    """Serve the demo UI with an embedded JWT token.
    
    Requires HTTP Basic Authentication. The browser will prompt for
    username and password. Upon successful authentication, a JWT token
    is generated and embedded into the HTML response for use by the
    frontend JavaScript.
    """
    token = generate_jwt(auth_settings.app_key)
    html_content = INDEX_HTML_TEMPLATE.replace("[TOKEN]", token)
    return HTMLResponse(content=html_content)


@app.get("/chat/{chat_id}")
async def get_chat(
    chat_id: str,
    chatbot_service: ChatbotService = Depends(get_chatbot_service),
    _: dict = Depends(require_jwt),
):
    """Return the full message history for the provided ``chat_id``.

    Raises ``HTTPException`` with a ``404`` status code if the chat session does
    not exist in the configured checkpoint backend.
    """
    try:
        return await chatbot_service.get_chat_history(chat_id)
    except ChatNotFoundError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


@app.websocket("/ws")
async def websocket_endpoint(
    ws: WebSocket,
    chatbot_service: ChatbotService = Depends(get_chatbot_service_ws),
    product_catalog = Depends(get_product_catalog_ws),
):
    """Bi-directional chat channel used by the frontend.

    The client must supply a ``chat_id`` query parameter and a valid JWT token
    via the ``token`` query parameter when opening the connection
    (for example ``/ws?chat_id=abc123&token=eyJ...``).

    Messages are sent as UTF-8 text frames and should be JSON objects with
    the following shape::

        {
            "message": "User input text",
            "current_product_id": "optional-catalog-id"
        }

    ``message`` is required and ``current_product_id`` lets the agent enrich the
    conversation with product metadata. When a plain text payload is received it
    is treated as ``{"message": "...", "current_product_id": null}``.

    The server streams JSON snapshots back to the client via ``send_json``. Each
    snapshot contains the AI's latest response chunk and any structured
    ``ui_payload`` generated by the LangGraph workflow.
    """
    # Validate authentication and parameters before accepting connection
    validate_websocket_token(ws)
    chat_id = validate_chat_id(ws)

    # Handle the chat session
    await handle_websocket_session(ws, chat_id, chatbot_service, product_catalog)
